### ISSUE TITLE
Feature Request Summary

### ISSUE THREAD

**Issue by alexander-dubinski** [nickbosch/jammming#2]
### Criteria 1: Objective Section  
* _Score Level:_ 4
* _Comment(s):_ Objective is very clear, good.
 
### Criteria 2: Background Section
* _Score Level:_ 4
* _Comment(s):_ Background is very detailed and well thought out, no issues here.
 
### Criteria 3: Technical Design Section
* _Score Level:_ 4
* _Comment(s):_ Technical design does a great job of addressing each components and how it should be changed. The only issues I have with this I talk about in my comments in the caveats section.
 
### Criteria 4: Caveats Section
* _Score Level:_ 3
* _Comment(s):_ Caveats are well thought out and detailed, just like the rest of the document, however there is one caveat I think was not addressed. That is what to show on the UI while Spotify authenticates. There will certainly be some time between clicking the login button and getting a response from Spotify so I think there should some discussion on how to deal with this.
 
### Overall Score: 15/16
Overall excellent job! This was one of the most detailed feature requests I have seen, well done. Happy Coding!

**Comment by nickbosch** [comment]
Thanks for the feedback! It would definitely be a good idea to provide the user with some kind of feedback (loading bar/locking the interface) before the Spotify redirect occurs.
